---
title: "Assignment5"
author: "yq2205"
date: "11/14/2017"
output: html_document
---

```{r setup, include=FALSE}
#Install & call libraries
install.packages("party", "rpart")

library(rpart)
library(party)
```
```{r}
#PART I
D1 <- read.csv("intelligent_tutor.csv")
##Classification Tree First we will build a classification tree to predict which students ask a teacher for help, which start a new session, or which give up, based on whether or not the student completed a session (D1$complete) and whether or not they asked for hints (D1$hint.y).
c.tree <- rpart(action ~ hint.y + complete, method="class", data=D1) #Notice the standard R notion for a formula X ~ Y

#Look at the error of this tree
printcp(c.tree)

#Plot the tree
post(c.tree, file = "tree.ps", title = "Session Completion Action: 1 - Ask teacher, 2 - Start new session, 3 - Give up")
```
```{r}
#PART II
#Regression Tree
#We want to see if we can build a decision tree to help teachers decide which students to follow up with, based on students' performance in Assistments. We will create three groups ("teacher should intervene", "teacher should monitor student progress" and "no action") based on students' previous use of the system and how many hints they use. To do this we will be building a decision tree using the "party" package. The party package builds decision trees based on a set of statistical stopping rules.
#Take a look at our outcome variable "score"

hist(D1$score)


```

```{r}
#Create a categorical outcome variable based on student score to advise the teacher using an "ifelse" statement

D1$advice <- ifelse(D1$score <=0.4, "intervene", ifelse(D1$score > 0.4 & D1$score <=0.8, "monitor", "no action"))
```
```{r}
#Build a decision tree that predicts "advice" based on how many problems students have answered before, the percentage of those problems they got correct and how many hints they required

score_ctree <- ctree(factor(advice) ~ prior_prob_count + prior_percent_correct + hints, D1)

```

```{r}
#Plot tree

plot(score_ctree)

# Question: Please interpret the tree, which two behaviors do you think the teacher should most closely pay attemtion to?
# Answer: from the tree, students do not request hints from teachers with lowerer prior correct percent should be paied the most attention.
```
```{r}
#Test Tree Upload the data "intelligent_tutor_new.csv". This is a data set of a differnt sample of students doing the same problems in the same system. We can use the tree we built for the previous data set to try to predict the "advice" we should give the teacher about these new students.

#Upload new data

D2 <- read.csv("intelligent_tutor_new.csv")

#Generate predicted advice for new students based on tree generated from old students

D2$prediction <- predict(score_ctree, D2)
```
```{r}
#PART III
#Compare the predicted advice with the actual advice that these studnts recieved. What is the difference between the observed and predicted results?
#recode the predicted advice
D1$advice[D1$advice=="no action"]<-3
D1$advice[D1$advice=="monitor"]<-1
D1$advice[D1$advice=="intervene"]<-2

```

```{r}
#compare actual and predicted
D3<-ifelse(D1$action==D1$advice,1,0)
sum(D3)

#After comparing the differences of the actual and predicted advice, I found 128 out of 378 observations are different.
```



